# Generated by Django 4.2.2 on 2023-06-06 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_img', models.CharField(max_length=50)),
                ('src', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SegmetOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.image')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('installation', models.CharField(max_length=100)),
                ('sockets_count', models.IntegerField()),
                ('socket_type', models.CharField(max_length=100)),
                ('power', models.CharField(max_length=100)),
                ('remote_control', models.CharField(max_length=100)),
                ('images', models.ManyToManyField(to='frontend.image')),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=256)),
                ('header_text_main', models.CharField(max_length=256)),
                ('header_text', models.CharField(max_length=256)),
                ('header_body', models.CharField(blank=True, max_length=256)),
                ('header_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_header_images', to='frontend.image')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_images', to='frontend.image')),
                ('segmets_of_work', models.ManyToManyField(blank=True, to='frontend.segmetofwork')),
            ],
        ),
    ]
