# Generated by Django 4.2.2 on 2023-06-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dev',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
