# Generated by Django 4.2.2 on 2023-06-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_product_dev'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOrQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
